<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Boxes, Cable, KeyRound, Plus, RefreshCw, Server, Sparkles } from 'lucide-vue-next'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'
import { api, type Entity } from '../services/api'
import { useAppStore } from '../stores/app'

const store=useAppStore(),tab=ref<'models'|'mcp'|'skills'>('models'),endpoints=ref<Entity[]>([]),extensions=ref<Entity[]>([]),skills=ref<Entity[]>([]),showForm=ref(false)
const endpointForm=reactive({name:'',provider_type:'openai-compatible',base_url:'',api_key:'',default_model:'',headersText:'{}',optionsText:'{}',timeout_seconds:90,enabled:true})
const mcpForm=reactive({name:'',description:'',transport:'http',url:'',command:'',argsText:'[]'})
const skillForm=reactive({name:'',description:'',version:'1.0.0',instructions:''})
async function load(){store.loading(true);try{[endpoints.value,extensions.value,skills.value]=await Promise.all([api.get('/model-endpoints'),api.get('/extensions'),api.get('/skills')])}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
async function saveEndpoint(){store.loading(true);try{const created:Entity=await api.post('/model-endpoints',{name:endpointForm.name,provider_type:endpointForm.provider_type,base_url:endpointForm.base_url,api_key:endpointForm.api_key,default_model:endpointForm.default_model,headers:JSON.parse(endpointForm.headersText||'{}'),request_options:JSON.parse(endpointForm.optionsText||'{}'),timeout_seconds:endpointForm.timeout_seconds,enabled:endpointForm.enabled});endpoints.value=[created,...endpoints.value.filter(item=>item.id!==created.id)];store.notify('模型 API 接口已安全保存并显示');showForm.value=false;await load()}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
async function testEndpoint(id:string){store.loading(true);try{const result:Entity=await api.post(`/model-endpoints/${id}/test`);store.notify(result.status==='healthy'?'接口连接正常':result.error,result.status==='healthy'?'success':'error');await load()}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
async function saveMcp(){store.loading(true);try{const config=mcpForm.transport==='http'?{transport:'http',url:mcpForm.url}:{transport:'stdio',command:mcpForm.command,args:JSON.parse(mcpForm.argsText||'[]')};await api.post('/extensions',{name:mcpForm.name,kind:'mcp',description:mcpForm.description,config,permissions:['network','tools']});store.notify('MCP 服务已注册');showForm.value=false;await load()}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
async function testExtension(id:string){store.loading(true);try{const result:Entity=await api.post(`/extensions/${id}/test`);store.notify(result.status==='healthy'?'MCP 握手成功':result.error,result.status==='healthy'?'success':'error');await load()}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
async function saveSkill(){store.loading(true);try{await api.post('/skills',skillForm);store.notify('Skill 已创建');showForm.value=false;await load()}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
async function sync(kind:'skills'|'plugins'){store.loading(true);try{await api.post(kind==='skills'?'/skills/sync':'/extensions/sync-plugins');store.notify('本地目录同步完成');await load()}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
onMounted(load)
</script>

<template>
  <PageHeader eyebrow="EXTENSIBILITY" title="扩展与模型" description="集中管理自定义大模型 API、MCP 服务、插件与可复用 Skills。"><button class="btn btn-primary" @click="showForm=true"><Plus :size="15" />添加{{ tab==='models'?'模型接口':tab==='mcp'?' MCP':' Skill' }}</button></PageHeader>
  <div class="card"><div class="tabs"><button class="tab" :class="{active:tab==='models'}" @click="tab='models';showForm=false"><Server :size="14" style="vertical-align:middle" /> 模型 API</button><button class="tab" :class="{active:tab==='mcp'}" @click="tab='mcp';showForm=false"><Cable :size="14" style="vertical-align:middle" /> MCP 与插件</button><button class="tab" :class="{active:tab==='skills'}" @click="tab='skills';showForm=false"><Sparkles :size="14" style="vertical-align:middle" /> Skills</button></div>

    <div v-if="tab==='models'" class="card-body">
      <div class="notice" style="margin-bottom:15px">支持任意 OpenAI Chat Completions 兼容接口。每个 Agent 可绑定不同 Endpoint；API Key 加密后存入 SQLite，界面和列表接口不会返回明文。</div>
      <div class="grid grid-3"><article v-for="item in endpoints" :key="item.id" class="card" style="box-shadow:none"><div class="card-body"><div style="display:flex;justify-content:space-between"><div class="metric-icon"><KeyRound :size="18" /></div><StatusBadge :status="item.health" /></div><h3 style="font-size:14px;color:#153b62">{{ item.name }}</h3><p style="font-size:10px;color:#6b8095;word-break:break-all">{{ item.base_url }}</p><span class="tag">{{ item.default_model }}</span><span class="tag">{{ item.has_api_key?'已配置密钥':'无密钥' }}</span><button class="btn btn-sm" style="width:100%;margin-top:13px" @click="testEndpoint(item.id)">测试连通性</button></div></article><div v-if="!endpoints.length" class="empty">尚未添加真实模型接口；Agent 默认使用离线演示模型。</div></div>
    </div>
    <div v-if="tab==='mcp'" class="card-body"><div style="display:flex;justify-content:flex-end;margin-bottom:10px"><button class="btn btn-sm" @click="sync('plugins')"><RefreshCw :size="13" />同步本地插件</button></div><div class="list-stack"><div v-for="item in extensions" :key="item.id" class="list-item"><div style="display:flex;gap:11px"><div class="metric-icon"><Boxes :size="18" /></div><div><strong>{{ item.name }}</strong><p>{{ item.kind.toUpperCase() }} · {{ item.description }}</p></div></div><div style="display:flex;gap:8px;align-items:center"><StatusBadge :status="item.health" /><button v-if="item.kind==='mcp'" class="btn btn-sm" @click="testExtension(item.id)">连接测试</button></div></div><div v-if="!extensions.length" class="empty">尚未接入 MCP 或插件</div></div></div>
    <div v-if="tab==='skills'" class="card-body"><div style="display:flex;justify-content:flex-end;margin-bottom:10px"><button class="btn btn-sm" @click="sync('skills')"><RefreshCw :size="13" />同步 SKILL.md</button></div><div class="grid grid-3"><article v-for="item in skills" :key="item.id" class="card" style="box-shadow:none"><div class="card-body"><Sparkles :size="19" color="#1769c2" /><h3 style="font-size:14px;color:#153b62;margin-bottom:5px">{{ item.name }}</h3><p style="font-size:11px;color:#667d93;line-height:1.55">{{ item.description }}</p><span class="tag">v{{ item.version }}</span></div></article></div></div>
  </div>

  <section v-if="showForm && tab==='models'" class="card" style="margin-top:20px"><div class="card-header"><h2>自定义大模型 API 接口</h2><button class="btn btn-sm" @click="showForm=false">取消</button></div><div class="card-body form-grid"><div class="field"><label>接口名称</label><input v-model="endpointForm.name" class="input" placeholder="讯飞星火 / 校内网关"></div><div class="field"><label>协议类型</label><select v-model="endpointForm.provider_type" class="select"><option value="openai-compatible">OpenAI Compatible</option><option value="spark-compatible">Spark Compatible</option><option value="custom">Custom Compatible</option></select></div><div class="field full"><label>Base URL</label><input v-model="endpointForm.base_url" class="input" placeholder="https://example.com/v1"></div><div class="field"><label>API Key</label><input v-model="endpointForm.api_key" type="password" class="input" autocomplete="new-password"></div><div class="field"><label>默认模型</label><input v-model="endpointForm.default_model" class="input" placeholder="model-name"></div><div class="field"><label>请求超时（秒）</label><input v-model.number="endpointForm.timeout_seconds" type="number" min="5" max="600" class="input"></div><div class="field"><label>接口状态</label><label style="display:flex;align-items:center;gap:8px;height:38px"><input v-model="endpointForm.enabled" type="checkbox"> 启用此接口</label></div><div class="field full"><label>自定义请求头（JSON）</label><textarea v-model="endpointForm.headersText" class="textarea" style="min-height:72px" /></div><div class="field full"><label>附加请求参数（JSON）</label><textarea v-model="endpointForm.optionsText" class="textarea" style="min-height:72px" /></div><div class="field full"><button class="btn btn-primary" @click="saveEndpoint">加密保存接口</button></div></div></section>
  <section v-if="showForm && tab==='mcp'" class="card" style="margin-top:20px"><div class="card-header"><h2>注册 MCP 服务</h2><button class="btn btn-sm" @click="showForm=false">取消</button></div><div class="card-body form-grid"><div class="field"><label>名称</label><input v-model="mcpForm.name" class="input"></div><div class="field"><label>Transport</label><select v-model="mcpForm.transport" class="select"><option value="http">Streamable HTTP</option><option value="stdio">stdio</option></select></div><div class="field full"><label>说明</label><input v-model="mcpForm.description" class="input"></div><div v-if="mcpForm.transport==='http'" class="field full"><label>服务 URL</label><input v-model="mcpForm.url" class="input"></div><template v-else><div class="field"><label>Command</label><input v-model="mcpForm.command" class="input"></div><div class="field"><label>Args（JSON 数组）</label><input v-model="mcpForm.argsText" class="input"></div></template><div class="field full"><button class="btn btn-primary" @click="saveMcp">注册服务</button></div></div></section>
  <section v-if="showForm && tab==='skills'" class="card" style="margin-top:20px"><div class="card-header"><h2>创建 Skill</h2><button class="btn btn-sm" @click="showForm=false">取消</button></div><div class="card-body form-grid"><div class="field"><label>名称</label><input v-model="skillForm.name" class="input"></div><div class="field"><label>版本</label><input v-model="skillForm.version" class="input"></div><div class="field full"><label>说明</label><input v-model="skillForm.description" class="input"></div><div class="field full"><label>执行指令</label><textarea v-model="skillForm.instructions" class="textarea" style="min-height:180px" /></div><div class="field full"><button class="btn btn-primary" @click="saveSkill">保存 Skill</button></div></div></section>
</template>
