<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { Check, FileClock, Plus, ShieldCheck, ShieldX, X } from 'lucide-vue-next'
import PageHeader from '../components/PageHeader.vue'
import StatusBadge from '../components/StatusBadge.vue'
import { api, type Entity } from '../services/api'
import { useAppStore } from '../stores/app'

const store=useAppStore(),tab=ref<'approvals'|'policies'|'audit'>('approvals'),approvals=ref<Entity[]>([]),policies=ref<Entity[]>([]),auditLogs=ref<Entity[]>([]),showForm=ref(false)
const form=reactive({name:'自定义审批策略',description:'按工具和风险等级控制 Agent 行为',priority:100,is_default:false,enabled:true,rulesText:JSON.stringify([{name:'只读自动执行',when:{risk_levels:['low']},decision:'auto'},{name:'写入人工确认',when:{risk_levels:['medium','high']},decision:'ask'},{name:'关键风险拒绝',when:{risk_levels:['critical']},decision:'deny'}],null,2)})
const parse=(value:string)=>{try{return JSON.parse(value||'[]')}catch{return[]}}
async function load(){store.loading(true);try{[approvals.value,policies.value,auditLogs.value]=await Promise.all([api.get('/approvals'),api.get('/approval-policies'),api.get('/audit?limit=100')])}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
async function decide(id:string,approved:boolean){store.loading(true);try{await api.post(`/approvals/${id}/decide`,{approved,decided_by:'local-user'});store.notify(approved?'操作已批准并执行':'操作已拒绝');await load()}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
async function savePolicy(){store.loading(true);try{await api.post('/approval-policies',{...form,rules:JSON.parse(form.rulesText)});store.notify('审批策略已创建');showForm.value=false;await load()}catch(e:any){store.notify(e.message,'error')}finally{store.loading(false)}}
const riskLabel:Record<string,string>={low:'低风险',medium:'中风险',high:'高风险',critical:'关键风险'}
onMounted(load)
</script>

<template>
  <PageHeader eyebrow="GOVERNANCE" title="安全治理" description="用可解释的审批策略、人工决策和不可省略的审计记录控制本地 Agent 行为。"><button v-if="tab==='policies'" class="btn btn-primary" @click="showForm=true"><Plus :size="15" />自定义策略</button></PageHeader>
  <div class="card"><div class="tabs"><button class="tab" :class="{active:tab==='approvals'}" @click="tab='approvals'"><ShieldCheck :size="14" style="vertical-align:middle" /> 审批中心</button><button class="tab" :class="{active:tab==='policies'}" @click="tab='policies'"><ShieldX :size="14" style="vertical-align:middle" /> 策略设计</button><button class="tab" :class="{active:tab==='audit'}" @click="tab='audit'"><FileClock :size="14" style="vertical-align:middle" /> 审计日志</button></div>
    <div v-if="tab==='approvals'" class="card-body"><div class="notice" style="margin-bottom:15px">批准只对当前请求生效，不会永久扩大 Agent 权限。关键风险命令会被运行时二次阻止。</div><div class="list-stack"><article v-for="item in approvals" :key="item.id" class="list-item"><div><strong>{{ item.summary }}</strong><p>{{ riskLabel[item.risk_level] || item.risk_level }} · {{ item.action_type }} · {{ new Date(item.created_at).toLocaleString('zh-CN') }}</p></div><div style="display:flex;align-items:center;gap:8px"><StatusBadge :status="item.status" /><template v-if="item.status==='pending'"><button class="btn btn-sm btn-primary" @click="decide(item.id,true)"><Check :size="13" />批准</button><button class="btn btn-sm btn-danger" @click="decide(item.id,false)"><X :size="13" />拒绝</button></template></div></article><div v-if="!approvals.length" class="empty"><ShieldCheck :size="30" /><br>当前没有审批请求</div></div></div>
    <div v-if="tab==='policies'" class="card-body"><div class="grid grid-3"><article v-for="item in policies" :key="item.id" class="card" style="box-shadow:none"><div class="card-body"><div style="display:flex;justify-content:space-between"><ShieldCheck :size="20" color="#1769c2" /><span v-if="item.is_default" class="tag">系统默认</span></div><h3 style="font-size:14px;color:#153b62">{{ item.name }}</h3><p style="font-size:11px;color:#667d93;min-height:34px">{{ item.description }}</p><div class="list-stack"><div v-for="rule in parse(item.rules_json)" :key="rule.name" style="padding:8px;background:#f6f9fc;border-radius:6px;font-size:10px;color:#48627b"><strong>{{ rule.name }}</strong><span style="float:right" :style="rule.decision==='deny'?'color:#b43b3b':rule.decision==='auto'?'color:#177c57':'color:#98640b'">{{ rule.decision.toUpperCase() }}</span></div></div></div></article></div></div>
    <div v-if="tab==='audit'" class="table-wrap"><table><thead><tr><th>时间</th><th>操作者</th><th>动作</th><th>资源</th><th>结果</th></tr></thead><tbody><tr v-for="item in auditLogs" :key="item.id"><td>{{ new Date(item.created_at).toLocaleString('zh-CN') }}</td><td>{{ item.actor }}</td><td>{{ item.action }}</td><td>{{ item.resource_type }}</td><td><StatusBadge :status="item.success?'completed':'failed'" /></td></tr></tbody></table></div>
  </div>
  <section v-if="showForm" class="card" style="margin-top:20px"><div class="card-header"><h2>自定义审批策略</h2><button class="btn btn-sm" @click="showForm=false">取消</button></div><div class="card-body form-grid"><div class="field"><label>策略名称</label><input v-model="form.name" class="input"></div><div class="field"><label>优先级（越小越优先）</label><input v-model.number="form.priority" type="number" class="input"></div><div class="field full"><label>说明</label><input v-model="form.description" class="input"></div><div class="field full"><label>匹配规则（JSON）</label><textarea v-model="form.rulesText" class="textarea" style="min-height:260px;font-family:Consolas,monospace" /><span class="field-help">规则按顺序匹配，条件支持 tools、risk_levels、agent_ids；决策支持 auto、ask、deny。</span></div><div class="field full"><button class="btn btn-primary" @click="savePolicy">保存策略</button></div></div></section>
</template>
